name: nf-core-hlatyping-1.2dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastqc=0.11.8
  - multiqc=1.7
  - optitype=1.3.2
  - yara=1.0.2
  - samtools=1.9
  - conda-forge::coincbc=2.9.9
  - conda-forge::r-rmarkdown=1.11
  - conda-forge::libiconv=1.15
